name: deploy
description:  Deploy a release

inputs:
  environment:
    description: Name of the environment
    required: true
  release_version:
    description: The release version
    required: true

runs:
  using: composite
  steps:
    - name: Download assets
      id: download_assets
      shell: bash
      run: |
        ls -la
        mkdir release-assets
        
        echo Downloading release assets
        gh release --repo ${{ github.repository }} download -O cdk.out.zip  ${{ inputs.release_version }}
        
        echo "Unzipping asset cdk.out.zip"
        unzip -q cdk.out.zip
        
    - name: Deploy to production
      id: deploy
      shell: bash
      run: |
        echo "Deploying ${{ inputs.release_version }} to ${{ inputs.environment }}"
      