name: main-deploy

on:
  release:
    types: [released]

jobs:  
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: echo
        run: | 
          mkdir assets
          gh release download -D assets -A zip
          ls -la assets
        shell: bash
