name: main-deploy

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Download assets
        id: download_assets
        run: |
          mkdir release-assets
          
          echo Downloading release assets
          gh release --repo ${{ github.repository }} download -D release-assets  ${{ github.event.release.tag_name }}

          echo Downloading release source code
          gh release --repo ${{ github.repository }} download -D release-assets -A zip ${{ github.event.release.tag_name }}
          
          echo "Unzip assets"          
          unzip release-assets/cdk.out.zip -d release-assets/
          unzip release-assets/${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.zip  -d release-assets/
        shell: bash

      - name: Deploy to production
        id: deploy_to_production
        run: |
          echo "Deploying ${{ github.event.release.tag_name }} to production"
        shell: bash