name: main-deploy

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: echo
        run: |
          mkdir release-assets          
          gh release --repo ${{ github.repository }} download -D release-assets ${{ github.event.release.name }}
          ls -l release-assets

          unzip release-assets/release.zip -d assets/
          ls -la release-assets

        shell: bash
