name: main-deploy

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: echo
        run: |
          mkdir release-assets
          
          echo Downloading release assets
          gh release --repo ${{ github.repository }} download -D release-assets ${{ github.event.release.name }}

          echo Downloading release source code
          gh release --repo ${{ github.repository }} download -D release-assets -A zip ${{ github.event.release.name }}
          
          echo XXXXXXXXXXXXXXXXXXXXXXXXXXX
          ls -la release-assets/ 

          unzip release-assets/cdk.out.zip -d release-assets/
          unzip release-assets/${{ github.event.repository.name }}-${{ github.event.release.name }}.zip  -d release-assets/

          echo XXXXXXXXXXXXXXXXXXXXXXXXXXX
          ls -la release-assets

        shell: bash
