name: main-deploy

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: echo
        run: |
          mkdir assets
          gh release --repo ${{ github.repository }} download -D assets -O release.zip -A zip
          unzip assets/release.zip -d assets/
          ls -la assets
          
        shell: bash
