name: main-ci

on:
  push:
    branches:
      - main

env:
  BUILD_VERSION: "1.0.${{github.run_number}}"
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_and_unit_test:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v3

      - name: Build and package
        uses: "./.github/template/build"
        with:
          release_version: ${{ env.BUILD_VERSION }}
      - run: echo Run unit test suite a
      - run: echo Run unit test suite b
      - run: echo Run unit test suite c


  deploy_dev:
    runs-on: ubuntu-latest
    environment: dev
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Deploy to dev
        uses: "./.github/template/deploy"
        with:
          release_version: ${{ env.BUILD_VERSION }}
          environment: dev

  integration_tests_dev:
    runs-on: ubuntu-latest
    needs: deploy_dev
    steps:
      - run: Run integration test suite a
      - run: Run integration test suite b
      - run: Run integration test suite c 