name: main-deploy

on:
  release:
    types: [released]

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    environment: prod
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Deploy to production
        uses: "./.github/template/deploy"
        with:
          release_version: ${{ github.event.release.tag_name }}
          environment: production
  smoke_tests_production:
    runs-on: ubuntu-latest
    needs: deploy_to_production
    steps:
      - run: Run all smoke tests