name: main-deploy

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: echo
        run: |
          mkdir release-assets
          gh release --repo ${{ github.repository }} download -O release-assets/release.zip -A zip
          unzip release-assets/release.zip -d assets/
          ls -la release-assets

        shell: bash
