name: main-deploy

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: deploy_to_test
        uses: "./.github/template/deploy"
        with:
          environment: test
          release-version:  ${{ github.event.release.tag_name }}