name: main-deploy

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: | 
          mkdir assets
          gh release download -D assets
          ls -la assets
        shell: bash
