name: main-deploy

on:
  release:
    types: [released]

jobs:  
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: echo
        run: | 
          echo "XXXXXXXXXXXXXXXX"
          echo ${{ github.repository }}
          echo "XXXXXXXXXXXXXXXX"
          mkdir assets
          REPO="KeyCore/kcms-bootstrap"
          gh release --repo ${REPO} download -D assets -A zip
          ls -la assets
        shell: bash
