name: main-ci

on:
  push:
    branches:
      - main

env:
  BUILD_VERSION: "1.0.${{github.run_number}}"
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v3

      - uses: "./.github/template/build"
        with:
          release_version: ${{ env.BUILD_VERSION }}

  deploy_test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download assets
        id: download_assets
        shell: bash
        run: |
          mkdir release-assets
          
          echo Downloading release assets
          gh release --repo ${{ github.repository }} download -D release-assets ${{ env.BUILD_VERSION }}

          echo Downloading release source code
          gh release --repo ${{ github.repository }} download -D release-assets -A zip ${{ env.BUILD_VERSION }}

          echo "Unzip assets"
          unzip -q 'release-assets/*.zip' -d release-assets/
        

      - name: Deploy to dev
        id: deploy_to_dev
        shell: bash
        run: |
          echo "Deploying ${{ env.BUILD_VERSION }} to dev"