name: main-deploy

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Download assets
        id: download_assets
        shell: bash
        run: |
          mkdir release-assets
          
          echo Downloading release assets
          gh release --repo ${{ github.repository }} download -D release-assets  ${{ github.event.release.tag_name }}

          echo Downloading release source code
          gh release --repo ${{ github.repository }} download -D release-assets -A zip ${{ github.event.release.tag_name }}
          
          echo "Unzip assets"
          unzip -q 'release-assets/*.zip' -d release-assets/  
        

      - name: Deploy to production
        id: deploy_to_production
        shell: bash
        run: |
          echo "Deploying ${{ github.event.release.tag_name }} to production"
        