name: main-ci

on:
  push:
    branches:
      - main

env:
  BUILD_VERSION: "1.0.${{github.run_number}}"
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v3

      - uses: "./.github/template/build"
        with:
          release_version: ${{ env.BUILD_VERSION }}

  deploy_dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/template/deploy"
        with:
          release_version: ${{ env.BUILD_VERSION }}
          environment: dev
