name: main-ci

on:
  push:
    branches:
      - main

env:
  BUILD_VERSION: "1.0.${{github.run_number}}"
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build version
        id: build_version
        run: echo ${{ env.BUILD_VERSION }}
        shell: bash

      - id: build
        name: Build and synthisize cdk app
        shell: bash
        run: |
          npm install
          npm run synth -- --context service-account=111111111111

      - name: Package release asset
        id: package_release
        shell: bash
        run: |
          zip -r cdk.out.zip ./cdk.out

      - name: Create github release
        id: create_release
        run: |
          gh release --repo ${{ github.repository }} create -p ${{ env.BUILD_VERSION }} cdk.out.zip
        shell: bash

  deploy_test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download assets
        id: download_assets
        run: |
          mkdir release-assets
          
          echo Downloading release assets
          gh release --repo ${{ github.repository }} download -D release-assets ${{ env.BUILD_VERSION }}

          echo Downloading release source code
          gh release --repo ${{ github.repository }} download -D release-assets -A zip ${{ env.BUILD_VERSION }}
          
          echo "Unzip assets"
          unzip -q release-assets/*.zip -d release-assets/
        shell: bash

      - name: Deploy to test
        id: deploy_to_test
        run: |
          echo "Deploying ${{ env.BUILD_VERSION }} to test"
        shell: bash        
