name: main-deploy

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: echo
        run: |
          mkdir assets
          gh release --repo ${{ github.repository }} download -D assets -A zip
          echo ${{ github.event.repository.name }}          
          echo ${{ github.event.release.name }}
          ls -la assets/${{ github.event.repository.name }}-${{ github.event.release.name }}.zip
        shell: bash
